version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: todos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: todos_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todos?schema=public
      PORT: 3000
      HOST: 0.0.0.0
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: todos_frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
